// <auto-generated />
namespace ComicBookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecomic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecomic));
        
        string IMigrationMetadata.Id
        {
            get { return "202001250209528_update-comic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
